export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const ARCHIVE_NOTE = 'ARCHIVE_NOTE';
export const UNARCHIVE_NOTES = 'UNARCHIVE_NOTES';
export const SEARCHED_NOTES = 'SEARCHED_NOTES';