export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const ARCHIVE_NOTE = 'ARCHIVE_NOTE';
export const SEARCHED_NOTES = 'SEARCHED_NOTES';
export const ADD_ARRAY_NOTES = 'ADD_ARRAY_NOTES';
export const ADD_ARRAY_ARCHIVE_NOTES = 'ADD_ARRAY_ARCHIVE_NOTES';
export const RESET_NOTE_STATE = 'RESET_NOTE_STATE';
export const RESET_ARCHIVE_STATE = 'RESET_ARCHIVE_STATE';
